-- PokemonData
--		name
--		catchrate
--		move
--		nature
--		type
--		status
--		item
--		map
-- RNGData
--		multspa
--		multspb
--		multspc
-- TableData
--		growth
--		attack
--		effort
--		misc
-- PickupData

HP_INTERNAL = 1;
ATK_INTERNAL = 2;
DEF_INTERNAL = 3;
SPE_INTERNAL = 4;
SPA_INTERNAL = 5;
SPD_INTERNAL = 6;

PokemonData = {
	name = {
		"??????????", "Grasshole", "Analgae", "Rectreem", "Arabomb", "Iguallah", "Lizakbar", "Ejacasm", 
		"Hosajack", "Condoom", "Squirrap", "Gampster", "Kengeon", "Frieden", "Corooster", 
		"Curicrawl", "Gutsicoon", "Gutsifly", "Larvades", "Proboskito", "Clovour", "Chanolour", 
		"Nauseon", "Hazmate", "Ebolable", "Pikotton", "Birdhouse", "Lanshil", "Middril", 
		"Shurismash", "Maymay", "Memenace", "Vandash", "Piguson", "Armando", "Muscledude", 
		"Tripecs", "Semdrop", "Semrust", "Furnazi", "Finasoven", "Troubait", "Tulure", 
		"Monstrap", "Pixila", "Fairileon", "Wedgard", "Knokedge", "Ribbizap", "Elephas", 
		"Seamapan", "Caroline", "Chompest", "Masdawg", "Pasdawg", "Spanke", "Anaconduke", 
		"Fishnism", "Sjwhale", "Chezetta", "Mozzamazel", "Krokling", "Krokizon", "Conchilla", 
		"Haremit", "Coolcube", "Tankube", "Fabkube", "Smogaroben", "Smoxilon", "Machmona", 
		"Bacub", "Urswine", "Moostatic", "Mooshock", "Pretzely", "Deemdow", "Dowster", 
		"Cheerly", "Cheerific", "Mennopaws", "Caracold", "Glacialynx", "Pengas", "Praeteur", 
		"Praestish", "Flowre", "Florious", "Juarecito", "Ponchito", "Somboludo", "Puppacti", 
		"Marionettl", "Tittai", "Octai", "Charagon", "Hyletrack", "Euphoreal", "Armowite", 
		"Praunch", "Karawn", "Mabster", "Tricient", "Tricillion", "Poizookie", "Toxiraptor", 
		"Sabreck", "Huntabre", "Pyralink", "Singlets", "Dubus", "Tripsius", "Miasmer", 
		"Miasmortor", "Cacademon", "Hanginy", "Chancer", "Unjoy", "Frosowl", "Whizzard", 
		"Drapillar", "Caparagon", "Mantrake", "Ogrelord", "Chantruth", "Inbitween", "Geigh", 
		"Jarape", "Spilefree", "Bongecko", "Mariguana", "Marleyzard", "Blobbos", "Ayylamo", 
		"Smellox", "Chasumo", "Oilslam", "Isissin", "Stuffowl", "Durkey", "Upchucken", 
		"Dragun", "Triggedon", "Cannonance", "Evacycle", "Foryu", "Scytill", "Baddon", 
		"Endranther", "Notridley", "Demiwaifu", "Clovenix", "Reptyke", "Rasclobber", "Batterex", 
		"Faeriock", "Sylvuin", "Oburonyxo", "Cloucat", "Felimbus", "Deathorus", "Knogoat", 
		"Knogrinyu", "Glasshot", "Glassannon", "Fluffyeti", "Yedoom", "Mirrostine", "Mudpants", 
		"Mudslacks", "Bukitlee", "Lossolith", "Mimimie", "Sprucifix", "Hulkan", "Nonite", 
		"Nonegative", "Nomaestro", "Dunkypea", "Burdmen", "Nutzboltz", "Kuklux", "Kuklan", 
		"Flameboyan", "Piicee", "Sonnanos", "Plebbles", "Sapleaf", "Ignut", "Phantash", 
		"Polossus", "Hitmonana", "Ballacle", "Barbarkley", "Kekroach", "Rekroach", "Ricosheep", 
		"Ricosuave", "Spaghefant", "Crystaquil", "Crystaking", "Fontaba", "Floconut", "Sappalm", 
		"Roynapalm", "Manateet", "Manatorque", "Manatank", "Anonymouse", "Motherfuck", "Ninoop", 
		"Draconius", "Ticktac", "Eareticle", "Scythear", "Cozload", "Snugware", "Fleespecs", 
		"Honrade", "Embortion", "Premantom", "Galavik", "Galavire", "Galaviste", "Pollefin", 
		"Florigrace", "Lasslee", "Wifemin", "Uwotto", "Venowatt", "Vaultevour", "Semdemen", 
		"Dragking", "Kuuroba", "Baitmaster", "Spookster", "Spookeer", "Spookzilla", "Derpato", 
		"Retater", "Potarded", "Sadfish", "Deloris", "Oreon", "Farfigtron", "Regirode", 
		"Regimelt", "Regirust", "Jewipede", "Vivaiger", "Heliofug", "Adesign", "Vyglass", 
		"?", "?", "?", "?", "?", "?", "?", 
		"?", "?", "?", "?", "?", "?", "?", 
		"?", "?", "?", "?", "?", "?", "?", 
		"?", "?", "?", "Sadrog", "Smugrok", "Peperee", "Hodtog", 
		"Wienebark", "Saudoge", "Gnarrk", "Corsharrk", "Davyjaws", "Humpunny", "Bunnorgy", 
		"Emelgy", "Fedorawk", "FaZeagle", "Catikillar", "Tikoon", "Oogabuga", "Ebining", 
		"Emplyin", "Upbote", "Upbeddit", "Flipbird", "Wheygle", "Gangnome", "Ruselamp", 
		"Mehndior", "Tunakking", "Pyongnome", "Bruhkid", "Cakupple", "Fondupple", "Shroofle", 
		"Ubruh", "Walruse", "Docee", "Donutsteel", "Bulbapedo", "Wastenaut", "Cirpent", 
		"Traumobra", "Militant", "Hofucno", "Hornigiri", "Falcaptain", "Snuffant", "Lizascoop", 
		"Gynuke", "Rainglock", "Fireshitwi", "Beatmarine", "Substarr", "Warney", "Banageddon", 
		"Maripyro", "Confirmabi", "Betacluck", "Thundacock", "Twinfowl", "Hopault", "Araketsu", 
		"Fresrye", "Dedwheat", "Wantnaut", "Cansumor", "Chromox", "Pitayen", "Dragaya", 
		"Avianjoin", "Illuminowl", "Tarditank", "Iplora", "Cthullord", "Quiboom", "Senketula", 
		"Cokemmoth", "Grimdak", "Nutjobber", "Deisnutz", "Reptrill", "Faptime", "Shiriman", 
		"Illumatrix", "Typobop", "Pearchie", "Reagain", "Ormite", "Housant", "Baloofang", 
		"Socckat", "Egylamp", "Apartmant", "Fuermiga", "Viristal", "Missletoe", "Hohohoming", 
		"Flaa", "Frutagon", "Biteki", "Sesquatch", "Dreameme", "Shiggydig", "Signot", 
		"Randomix", "Yeerex", "Fireshi", "Fefeion", "Feferun", "Jerkle", "Acufront", 
		"Spargle", "Spedo", "Hornicier", "Hornititan", "Preasu", "Undastand", "Walruskie", 
		"Diobat", "Warudio", "Fireshitre", "Slugbud", "Slughug", "Slugfugg", "Skeletroll", 
		"Spookscare", "Goryannus", "Lankong", "Ballankey", "Niterpent", "Griffawork", "Boarnograf", 
		"Funnedong", "Narwhiz", "Admoot", "Tentaquil", "Rolango", 
	},
	move = {
		"-", "Pound", "Karate Chop", "Doubleslap", "Comet Punch", "Mega Punch", "Pay Day",
		"Fire Punch", "Ice Punch", "Thunderpunch", "Scratch", "Vicegrip", "Guillotine",
		"Razor Wind", "Swords Dance", "Cut", "Gust", "Wing Attack", "Whirlwind", "Fly",
		"Bind", "Slam", "Vine Whip", "Stomp", "Double Kick", "Mega Kick", "Jump Kick",
		"Rolling Kick", "Sand-Attack", "Headbutt", "Horn Attack", "Fury Attack", "Horn Drill",
		"Tackle", "Body Slam", "Wrap", "Take Down", "Thrash", "Double-Edge", "Tail Whip",
		"Poison Sting", "Twineedle", "Pin Missile", "Leer", "Bite", "Growl", "Roar", "Sing",
		"Supersonic", "Sonicboom", "Disable", "Acid", "Ember", "Flamethrower", "Mist", "Water Gun",
		"Hydro Pump", "Surf", "Ice Beam", "Blizzard", "Psybeam", "Bubblebeam", "Aurora Beam",
		"Hyper Beam", "Peck", "Drill Peck", "Submission", "Low Kick", "Counter", "Seismic Toss",
		"Strength", "Absorb", "Mega Drain", "Leech Seed", "Growth", "Razor Leaf", "Solarbeam",
		"Poisonpowder", "Stun Spore", "Sleep Powder", "Petal Dance", "String Shot", "Dragon Rage",
		"Fire Spin", "Thundershock", "Thunderbolt", "Thunder Wave", "Thunder", "Rock Throw",
		"Earthquake", "Fissure", "Dig", "Toxic", "Confusion", "Psychic", "Hypnosis",
		"Meditate", "Agility", "Quick Attack", "Rage", "Teleport", "Night Shade", "Mimic",
		"Screech", "Double Team", "Recover", "Harden", "Minimize", "Smokescreen", "Confuse Ray",
		"Withdraw", "Defense Curl", "Barrier", "Light Screen", "Haze", "Reflect", "Focus Energy",
		"Bide", "Metronome", "Mirror Move", "Selfdestruct", "Egg Bomb", "Lick", "Smog", "Sludge",
		"Bone Club", "Fire Blast", "Waterfall", "Clamp", "Swift", "Skull Bash", "Spike Cannon",
		"Constrict", "Amnesia", "Kinesis", "Softboiled", "Hi Jump Kick", "Glare", "Dream Eater",
		"Poison Gas", "Barrage", "Leech Life", "Lovely Kiss", "Sky Attack", "Transform", "Bubble",
		"Dizzy Punch", "Spore", "Flash", "Psywave", "Splash", "Acid Armor", "Crabhammer", "Explosion",
		"Fury Swipes", "Bonemerang", "Rest", "Rock Slide", "Hyper Fang", "Sharpen", "Conversion",
		"Tri Attack", "Super Fang", "Slash", "Substitute", "Struggle", "Sketch", "Triple Kick",
		"Thief", "Spider Web", "Mind Reader", "Nightmare", "Flame Wheel", "Snore", "Curse", "Flail",
		"Conversion 2", "Aeroblast", "Cotton Spore", "Reversal", "Spite", "Powder Snow", "Protect",
		"Mach Punch", "Scary Face", "Feint Attack", "Sweet Kiss", "Belly Drum", "Sludge Bomb", "Mud-Slap",
		"Octazooka", "Spikes", "Zap Cannon", "Foresight", "Destiny Bond", "Perish Song", "Icy Wind",
		"Detect", "Bone Rush", "Lock-On", "Outrage", "Sandstorm", "Giga Drain", "Endure", "Charm",
		"Rollout", "False Swipe", "Swagger", "Milk Drink", "Spark", "Fury Cutter", "Steel Wing",
		"Mean Look", "Attract", "Sleep Talk", "Heal Bell", "Return", "Present", "Frustration",
		"Safeguard", "Pain Split", "Sacred Fire", "Magnitude", "Dynamicpunch", "Megahorn", "Dragonbreath",
		"Baton Pass", "Encore", "Pursuit", "Rapid Spin", "Sweet Scent", "Iron Tail", "Metal Claw",
		"Vital Throw", "Morning Sun", "Synthesis", "Moonlight", "Hidden Power", "Cross Chop",
		"Twister", "Rain Dance", "Sunny Day", "Crunch", "Mirror Coat", "Psych Up", "Extremespeed",
		"Ancientpower", "Shadow Ball", "Future Sight", "Rock Smash", "Whirlpool", "Beat Up", "Fake Out",
		"Uproar", "Stockpile", "Spit Up", "Swallow", "Heat Wave", "Hail", "Torment", "Flatter",
		"Will-O-Wisp", "Memento", "Facade", "Focus Punch", "Smellingsalt", "Follow Me", "Nature Power",
		"Charge", "Taunt", "Helping Hand", "Trick", "Role Play", "Wish", "Assist", "Ingrain",
		"Superpower", "Magic Coat", "Recycle", "Revenge", "Brick Break", "Yawn", "Knock Off",
		"Endeavor", "Eruption", "Skill Swap", "Imprison", "Refresh", "Grudge", "Snatch", "Secret Power",
		"Dive", "Arm Thrust", "Camouflage", "Tail Glow", "Luster Purge", "Mist Ball", "Featherdance",
		"Teeter Dance", "Blaze Kick", "Mud Sport", "Ice Ball", "Needle Arm", "Slack Off", "Hyper Voice",
		"Poison Fang", "Crush Claw", "Blast Burn", "Hydro Cannon", "Meteor Mash", "Astonish",
		"Weather Ball", "Aromatherapy", "Fake Tears", "Air Cutter", "Overheat", "Odor Sleuth",
		"Rock Tomb", "Silver Wind", "Metal Sound", "Grasswhistle", "Tickle", "Cosmic Power",
		"Water Spout", "Signal Beam", "Shadow Punch", "Extrasensory", "Sky Uppercut", "Sand Tomb",
		"Sheer Cold", "Muddy Water", "Bullet Seed", "Aerial Ace", "Icicle Spear", "Iron Defense",
		"Block", "Howl", "Dragon Claw", "Frenzy Plant", "Bulk Up", "Bounce", "Mud Shot", "Poison Tail",
		"Covet", "Volt Tackle", "Magical Leaf", "Water Sport", "Calm Mind", "Leaf Blade", "Dragon Dance",
		"Rock Blast", "Shock Wave", "Water Pulse", "Doom Desire", "Psycho Boost", "Ow The Edge",
		"Air Slash", "Aqua Jet", "Aqua Tail", "Aura Sphere", "Avalanche", "Brave Bird", "Bug Buzz",
		"Bullet Punch", "Charge Beam", "Close Combat", "Cross Poison", "Dark Pulse", "Discharge",
		"Draco Meteor", "Dragon Pulse", "Drain Punch", "Earth Power", "Energy Ball", "Focus Blast",
		"Force Palm", "Giga Impact", "Grass Knot", "Gunk Shot", "Hammer Arm", "Head Smash", "Ice Shard",
		"Iron Head", "Lava Plume", "Magnet Bomb", "Mud Bomb", "Nasty Plot", "Night Slash", "Ominous Wind",
		"Power Gem", "Power Whip", "Psycho Cut", "Rock Climb", "Rock Polish", "Rock Wrecker", "Roost",
		"Seed Bomb", "Shadow Claw", "Shadow Sneak", "Vacuum Wave", "X-Scissor", "Zen Headbutt", "Switcheroo",
		"Drill Run", "Bulldoze", "Electroweb", "Flame Charge", "Frost Breath", "Heart Stamp", "Hone Claws",
		"Horn Leech", "Coil", "Hurricane", "Icicle Crash", "Work Up", "Quiver Dance", "Ice Hammer",
		"Low Sweep", "Snarl", "Struggle Bug", "Steamroller", "Storm Throw", "Venoshock",
		"Wild Charge", "Poison Jab", "Acid Spray", "Fiery Dance", "Clear Smog",
		"Leaf Storm", "Stone Edge", "Payback", "Fire Fang", "Ice Fang", "Thunder Fang",
		"Flare Blitz", "Inferno", "Hex", "Dual Chop", "Double Hit", "Cotton Guard",
		"Acrobatics", "Flame Burst", "U-turn", "Volt Switch", "Dragon Tail", "Circle Throw",
		"Mirror Shot", "Wood Hammer", "Heal Pulse", "Flash Cannon", "Bug Bite", "Pluck",
		"Shell Smash", "Rage Powder", "Wake-Up Slap", "Razor Shell", "Copycat", "Defog",
		"Sucker Punch", "Scald", "Brine", "Fairy Wind", "BabyDollEyes", "Play Rough", "Moonblast",
		"Drain Kiss", "Dazzle Gleam", "Disarmer Cry", "Stealth Rock", "Toxic Spikes", "Falcon Punch",
		"Riot Shield", "Swindle", "Boomburst", "Incinerate", "Power Punch", "Gastro Acid",
		"V-Create", "Accelerock", "Shadow Bone", "Shift Gear", "Sticky Web", "Stored Power",
		"Acupressure", "Punishment", "Foul Play", "Enema", "Come n' Go", "Holy Duty", "Punch Out",
		"Erosion Wave", "Strato Blade", "Super Snore", "Toxiravage", "Meme", "For You", "Spook Out",
		"Decay Drain", "Dildo Cannon", "Regenerate", "Futaba Break", "Puke Blood", "Chaos Dunk",
		"Daily Dose", "Fizzbitch", "Fire Bomb", "Overenergize", "An Attack", "Lactose Shot",
		"Trigger", "Toke", "Shitpost", "Attack Order", "Defend Order", "Heal Order", "Captivate",
		"Round", "Origin Pulse", "Cliff Blades", "Guard Swap", "Steam Erupt", "Metal Burst",
		"Me First", "Power Swap", "Power Trick", "Psycho Shift", "Wring Out", "Kings Shield",
		"Psystrike", "Autotomize", "Diamondstorm", "Sludge Wave", "Heavy Slam", "Synchronoise",
		"Electro Ball", "Tail Slap", "Entrainment", "Night Daze", "Echoed Voice", "Land's Wrath",
		"Oblivionwing", "Heart Swap", "Crush Grip", "Sacred Sword", "Heat Crash", "Head Charge",
		"Techno Blast", "Relic Song", "Secret Sword", "Glaciate", "Bolt Strike", "Blue Flare",
		"Freeze Shock", "Ice Burn", "Gear Grind", "Fusion Flare", "Fusion Bolt", "Fell Stinger",
		"Noble Roar", "Draco Ascent", "Parting Shot", "Topsy-Turvy", "Core Enforce", "Chatter",
		"Confide", "Water Star", "Mystic Fire", "Spiky Shield", "EerieImpulse", "Hold Back",
		"Infestation", "Magma Storm", "1000 Arrows", "1000 Waves", "Para Charge", "Searing Shot",
		"Seed Flare", "Play Nice", "Anchor Shot", "Aurora Veil", "Baneful Bunk", "Beak Blast",
		"Brutal Swing", "Burn Up", "Clang Scales", "Dark Lariat", "Draco Hammer", "Fire Lash",
		"First Press", "Fleur Cannon", "Floral Heal", "Gear Up", "Horsepower", "Dragon Rush",
		"Laser Focus", "Leafage", "Liquidation", "Lunge", "Geist Beam", "Sleazy Spore", "Nature's Mad",
		"Pollen Puff", "Power Trip", "Prism Laser", "Psychic Fang", "Purify", "Revel Dance",
		"Leaf Tornado", "Shell Trap", "Shore Up", "Smart Strike", "Solar Blade", "Sparkle Aria",
		"Spect Thief", "Speed Swap", "Soul Shackle", "Slime Gulp", "StompTantrum", "Strength Sap",
		"Sunsteel Ram", "Tearful Look", "Throat Chop", "Toxic Thread", "Trop Kick", "Zing Zap",
		"Elec Field", "Grassy Field", "Misty Field", "Psych Field", "Inverse Room", "Fruit Punch",
		"Last Resort", "Trick Room", "Magic Room", "Wonder Room", "Crafty Guard", "Mat Block",
		"Quick Guard", "Wide Guard", "Aqua Ring", "Dragon Fist", "Belch", "Lick Clean", "Speed Weed",
		"Flying Press", "Gravity", "Guard Split", "Heal Block", "Ion Deluge", "Lucky Chant", "Magnet Rise", 
		"Overbite", "Powder", "Power Split", "Reflect Type", "Simple Beam", "Soak", "Telekinesis",
		"TrickoTreat", "Venom Drench", "Forest Curse", "Mind Blown", "Photongeyser", "Plasma Fists",
		"Electrify", "1000 Folds", "Fairy Lock", "Light o Ruin", "Trump Card", "Warhead", "Baddy Bad",
		"Weird Flex", "Scorch Earth", "Miracle Eye", "Healing Wish", "Lunar Dance", "Tailwind",
		"Worry Seed", "Geomancy", "Flower Guard", "Rototiller", "Assurance", "Dark Void", "Feint",
		"PhantomForce", "Shadow Force", "Roar of Time", "Spacial Rend", "Final Gambit", "Petal Storm",
		"Nuzzle", "Retaliate", "Celebrate", "Hulk Up", "Freeze-Dry", "Psyshock", "Natural Gift",
		"Chip Away", "Smack Down", "Gyro Ball", "Space Fury", "Space Hole", "Focus Munch", "Mop",
		"Quick Sand", "Think Fast", "Boltbeam", "Checkem", "Pixie Pummel", "Iron Bash", "Gay Agenda",
		"Spooperpower", "Great Rage", "Wow Wiener", "Plunder", "Blobby Bop", "Ban Hammer", "Homerun Bat",
		"Sudoku", "Elbow Drop"
	},
	moveLookup = {},
	nature = {
		"Hardy", "Lonely", "Brave", "Adamant", "Naughty",
		"Bold", "Docile", "Relaxed", "Impish", "Lax",
		"Timid", "Hasty", "Serious", "Jolly", "Naive",
		"Modest", "Mild", "Quiet", "Bashful", "Rash",
		"Calm", "Gentle", "Sassy", "Careful", "Quirky"
	},
	natureLookup = {},
	type = {
		"Normal","Fighting","Flying","Poison","Ground",
		"Rock","Bug","Ghost","Steel","???",
		"Fire","Water","Grass","Electric",
		"Psychic","Ice","Dragon","Dark","Type 18",
		"Type 19","Type 20","Type 21","Type 22","Fairy"
	},
	status = {
		"None","Sleep","Poison","Burn","Freeze",
		"Paralysis","Bad Poison"
	},
	ability = {
		"-------", "Stench", "Drizzle", "Speed Boost", "Battle Armor", "Sturdy", "Damp", "Limber",
		"Sand Veil", "Static", "Volt Absorb", "Water Absorb", "Oblivious", "Cloud Nine", "Compoundeyes",
		"Insomnia", "Color Change", "Immunity", "Flash Fire", "Shield Dust", "Own Tempo", "Suction Cups",
		"Intimidate", "Shadow Tag", "Rough Skin", "Wonder Guard", "Levitate", "Effect Spore", "Synchronize",
		"Clear Body", "Natural Cure", "Lightningrod", "Serene Grace", "Swift Swim", "Chlorophyll",
		"Illuminate", "Trace", "Huge Power", "Poison Point", "Inner Focus", "Magma Armor", "Water Veil",
		"Magnet Pull", "Soundproof", "Rain Dish", "Sand Stream", "Pressure", "Thick Fat", "Early Bird",
		"Flame Body", "Run Away", "Keen Eye", "Hyper Cutter", "Pickup", "Truant", "Hustle", "Cute Charm",
		"Plus", "Minus", "Forecast", "Sticky Hold", "Shed Skin", "Guts", "Marvel Scale", "Liquid Ooze",
		"Overgrow", "Blaze", "Torrent", "Swarm", "Rock Head", "Drought", "Arena Trap", "Vital Spirit",
		"White Smoke", "Pure Power", "Shell Armor", "Cacophony", "Air Lock", "-------_2", "Skill Link",
		"Motor Drive", "Multiscale", "Technician", "Scrappy", "Super Luck", "Sniper", "Regenerator",
		"Prankster", "Adaptability", "Big Pecks", "Magic Bounce", "Reckless", "Sheer Force", "Iron Fist",
		"Rivalry", "Sand Force", "Solar Power", "Heatproof", "Dry Skin", "Tinted Lens", "Solid Rock",
		"Filter", "Infiltrator", "Download", "Poison Heal", "Ice Body", "Moody", "Hydration",
		"Healer", "Snow Cloak", "Tangled Feet", "Snow Warning", "Quick Feet", "Sap Sipper", "Overcoat",
		"Magic Guard", "Bulletproof", "Gale Wings", "Moxie", "Aftermath", "Cursed Body", "Gooey",
		"Mummy", "Iron Barbs", "Sand Rush", "Analytic", "No Guard", "Megalauncher", "Tough Claws",
		"Strong Jaw", "Victory Star", "Storm Drain", "Dark Aura", "Fairy Aura", "Aura Break",
		"Refrigerate", "Pixilate", "Aerilate", "Normalize", "Steelworker", "Water Bubble", "Fur Coat",
		"Fluffy", "Galvanize", "Grass pelt", "Defeatist", "Heavy Metal", "Light Metal", "Toxic Boost",
		"Flare Boost", "Unaware", "Flower Gift", "Mold Breaker", "Turboblaze", "Teravolt", "Liquid Voice",
		"Bad Dreams", "Anger Point", "Anticipation", "Forewarn", "Frisk", "Gluttony", "Klutz",
		"Leaf Guard", "Simple", "Slow Start", "Stall", "Steadfast", "Unburden", "Contrary", "Defiant",
		"Competitive", "Harvest", "Imposter", "Justified", "Pickpocket", "Poison Touch", "Rattled",
		"Unnerve", "Weak Armor", "Wonder Skin", "Protean", "Beast Boost", "Berserk", "Corrosion",
		"Dazzling", "Majestic", "Electrosurge", "Grassy Surge", "Innards Out", "Long Reach", "Merciless",
		"Misty Surge", "Neuroforce", "Psycho Surge", "Slush Rush", "Shadow Guard", "Stamina",
		"Surge Surfer", "Hair Tangle", "Triage", "Compaction", "More Room", "Battery", "Sweet Veil",
		"Suddenly", "Comatose", "Ghost Note", "Aroma Veil", "Soul-Heart", "Wimp Out", "Stakeout",
		"Receiver", "Cheek Pouch", "Magician", "Friend Guard", "Telepathy", "Wooden Guard", "Artificial",
		"An Ability", "Jewelry", "Big Guy", "Blademaster", "Admin Abuse", "Degenerate", "Bone Zone",
		"Flare Heal", "Shower Power", "Boombox", "Pozzed", "Pollution", "Degradation", "Woke", "Puppeteer",
		"Striker", "Madman", "Inversion", "Hydrophile", "Fire Exit", "Flower Veil", "Alchemy", "Metal Body",
		"Prism Armor", "Ball Fetch", "Concert", "Wait For It", "Gradient", "Any Ability", "Steam Engine"
	},
	item = {
		"????????", "Master Ball", "Ultra Ball", "Great Ball", "Poké Ball", "Safari Ball", "Net Ball",
		"Dive Ball", "Nest Ball", "Repeat Ball", "Timer Ball", "Luxury Ball", "Premier Ball", "Potion",
		"Antidote", "Burn Heal", "Ice Heal", "Awakening", "Paralyz Heal", "Full Restore", "Max Potion",
		"Hyper Potion", "Super Potion", "Full Heal", "Revive", "Max Revive", "Fresh Water", "Soda Pop",
		"Lemonade", "Moomoo Milk", "Energypowder", "Energy Root", "Heal Powder", "Revival Herb", "Ether",
		"Max Ether", "Elixir", "Max Elixir", "Lava Cookie", "Blue Flute", "Yellow Flute", "Red Flute",
		"Black Flute", "White Flute", "Berry Juice", "Sacred Ash", "Shoal Salt", "Shoal Shell", "Red Shard",
		"Blue Shard", "Yellow Shard", "Green Shard", "Quick Ball", "Dusk Ball", "Heal Ball", "Junk Ball",
		"Masta Ball", "Monster Ball", "Fast Ball", "Barbed Ball", "Rasta Ball", "B-Ball", "Rude Ball",
		"HP Up", "Protein", "Iron", "Carbos", "Calcium", "Rare Candy", "PP Up", "Zinc", "PP Max",
		"Magnet Ball", "Guard Spec.", "Dire Hit", "X Attack", "X Defend", "X Speed", "X Accuracy",
		"X Special", "Poké Doll", "Dream Ball", "Cellar Key", "Super Repel", "Max Repel", "Escape Rope",
		"Repel", "DDT Spray", "Rare Bone", "Grip Claw", "Destiny Knot", "Bottlecap", "Golden Cap",
		"Sun Stone", "Moon Stone", "Fire Stone", "Thunderstone", "Water Stone", "Leaf Stone", "Far Doll",
		"Tor Doll", "Metal Coat", "Up-Grade", "Tinymushroom", "Big Mushroom", "Binding Band", "Pearl",
		"Big Pearl", "Stardust", "Star Piece", "Nugget", "Heart Scale", "Gold Clover", "Clover Leaf",
		"Odd Dildo", "Pirate's Jug", "Porn Drive", "House Key", "Cursed Coin", "Custap Berry",
		"Lab Key", "Orange Mail", "Harbor Mail", "Glitter Mail", "Mech Mail", "Wood Mail", "Wave Mail",
		"Bead Mail", "Shadow Mail", "Tropic Mail", "Dream Mail", "Fab Mail", "Retro Mail", "Cheri Berry",
		"Chesto Berry", "Pecha Berry", "Rawst Berry", "Aspear Berry", "Leppa Berry", "Oran Berry",
		"Persim Berry", "Lum Berry", "Sitrus Berry", "Figy Berry", "Wiki Berry", "Mago Berry", "Aguav Berry",
		"Iapapa Berry", "Occa Berry", "Passho Berry", "Nanab Berry", "Rindo Berry", "Wacan Berry",
		"Pomeg Berry", "Kelpsy Berry", "Qualot Berry", "Hondew Berry", "Grepa Berry", "Tamato Berry",
		"Yache Berry", "Chople Berry", "Kebia Berry", "Nomel Berry", "Shuca Berry", "Coba Berry",
		"Watmel Berry", "Payapa Berry", "Tanga Berry", "Liechi Berry", "Ganlon Berry", "Salac Berry",
		"Petaya Berry", "Apicot Berry", "Lansat Berry", "Starf Berry", "Enigma Berry", "Charti Berry",
		"Kasib Berry", "Haban Berry", "Brightpowder", "White Herb", "Macho Brace", "Dream Pill",
		"Quick Claw", "Soothe Bell", "Mental Herb", "Choice Band", "King's Rock", "Silverpowder",
		"Amulet Coin", "Cleanse Tag", "Power Herb", "Big Faggot", "Bacon Strip", "Smoke Ball",
		"Everstone", "Focus Band", "Lucky Egg", "Scope Lens", "Iron Ball", "Leftovers", "Lagging Tail",
		"Light Ball", "Soft Sand", "Hard Stone", "Miracle Seed", "BlackGlasses", "Black Belt", "Magnet",
		"Mystic Water", "Sharp Beak", "Poison Barb", "Nevermeltice", "Spell Tag", "TwistedSpoon", "Charcoal",
		"Dragon Fang", "Silk Scarf", "Shed Shell", "Shell Bell", "Sea Incense", "Lax Incense", "Air Balloon",
		"Metal Powder", "Thicc Bone", "Bible", "Choice Specs", "Choice Scarf", "Life Orb", "Rocky Helmet",
		"Black Sludge", "Assault Vest", "Eviolite", "Colbur Berry", "Babiri Berry", "Chilan Berry",
		"Roseli Berry", "Expert Belt", "Flame Orb", "Toxic Orb", "Wide Lens", "Light Clay", "Razor Claw",
		"Suede Shoes", "Safety Specs", "Ability Pill", "Focus Sash", "Heat Rock", "Damp Rock", "Taco",
		"Weed", "Zoom Lens", "Cute Bow", "Katana", "Smooth Rock", "Icy Rock", "Terrain Ext.", "Weak Policy",
		"Sticky Barb", "Eject Button", "Coin Case", "Itemfinder", "Old Rod", "Good Rod", "Super Rod",
		"Ruse Ticket", "Normal Gem", "Walkman", "Fighting Gem", "Flying Gem", "Poison Gem", "Ground Gem",
		"Rock Gem", "Bug Gem", "Ghost Gem", "Steel Gem", "Fire Gem", "Burn Drive", "Chill Drive",
		"Douse Drive", "Shock Drive", "Room Key", "Water Gem", "Grass Gem", "Electric Gem", "Psychic Gem",
		"Fang Fossil", "Conch Fossil", "Ice Gem", "TM01", "TM02", "TM03", "TM04", "TM05", "TM06", "TM07",
		"TM08", "TM09", "TM10", "TM11", "TM12", "TM13", "TM14", "TM15", "TM16", "TM17", "TM18", "TM19",
		"TM20", "TM21", "TM22", "TM23", "TM24", "TM25", "TM26", "TM27", "TM28", "TM29", "TM30", "TM31",
		"TM32", "TM33", "TM34", "TM35", "TM36", "TM37", "TM38", "TM39", "TM40", "TM41", "TM42", "TM43",
		"TM44", "TM45", "TM46", "TM47", "TM48", "TM49", "TM50", "HM01", "HM02", "HM03", "HM04", "HM05", 
		"HM06", "HM07", "HM08", "Old Key", "Rusty Key", "Large Parcel", "Poop Flute", "Cage Key", "Axe",
		"Ban Hammer", "Raptor Claw", "Card Key", "Lift Key", "Tooth Fossil", "Horn Fossil", "Skelecharm",
		"Bicycle", "Town Map", "VS Seeker", "Fame Checker", "TM Case", "Berry Pouch", "Dragon Gem",
		"Battle Pass", "Ebin Pass", "Manifesto", "Dark Gem", "Fairy Gem", "Powder Jar", "Big Root", "Jar of Pee"
	},
	itemLookup = {},
	stats = {
		"HP", "Atk", "Def", "SpA", "SpD", "Spe"
	},
	statsInternal = {
		"HP", "Atk", "Def", "Spe", "SpA", "SpD"
	},
	statsInternalLookup = {},
	natureModifier = {
		{ATK_INTERNAL, ATK_INTERNAL},
		{ATK_INTERNAL, DEF_INTERNAL},
		{ATK_INTERNAL, SPE_INTERNAL},
		{ATK_INTERNAL, SPA_INTERNAL},
		{ATK_INTERNAL, SPD_INTERNAL},

		{DEF_INTERNAL, ATK_INTERNAL},
		{DEF_INTERNAL, DEF_INTERNAL},
		{DEF_INTERNAL, SPE_INTERNAL},
		{DEF_INTERNAL, SPA_INTERNAL},
		{DEF_INTERNAL, SPD_INTERNAL},

		{SPE_INTERNAL, ATK_INTERNAL},
		{SPE_INTERNAL, DEF_INTERNAL},
		{SPE_INTERNAL, SPE_INTERNAL},
		{SPE_INTERNAL, SPA_INTERNAL},
		{SPE_INTERNAL, SPD_INTERNAL},

		{SPA_INTERNAL, ATK_INTERNAL},
		{SPA_INTERNAL, DEF_INTERNAL},
		{SPA_INTERNAL, SPE_INTERNAL},
		{SPA_INTERNAL, SPA_INTERNAL},
		{SPA_INTERNAL, SPD_INTERNAL},

		{SPD_INTERNAL, ATK_INTERNAL},
		{SPD_INTERNAL, DEF_INTERNAL},
		{SPD_INTERNAL, SPE_INTERNAL},
		{SPD_INTERNAL, SPA_INTERNAL},
		{SPD_INTERNAL, SPD_INTERNAL}
	}
}

TableData = {
	growth = {1,1,1,1,1,1, 2,2,3,4,3,4, 2,2,3,4,3,4, 2,2,3,4,3,4},
	attack = {2,2,3,4,3,4, 1,1,1,1,1,1, 3,4,2,2,4,3, 3,4,2,2,4,3},
	effort = {3,4,2,2,4,3, 3,4,2,2,4,3, 1,1,1,1,1,1, 4,3,4,3,2,2},
	misc   = {4,3,4,3,2,2, 4,3,4,3,2,2, 4,3,4,3,2,2, 1,1,1,1,1,1}
}

for k, v in pairs(PokemonData.nature) do
	PokemonData.natureLookup[v:lower()] = k - 1;
end

for k, v in pairs(PokemonData.statsInternal) do
	PokemonData.statsInternalLookup[v:lower()] = k - 1;
end

for k, v in pairs(PokemonData.move) do
	PokemonData.moveLookup[v:lower():gsub("%s+", "")] = k - 1;
end

for k, v in pairs(PokemonData.item) do
	PokemonData.itemLookup[v:lower():gsub("%s+", "")] = k - 1;
end
