-- PokemonData
--		name
--		catchrate
--		move
--		nature
--		type
--		status
--		item
--		map
-- RNGData
--		multspa
--		multspb
--		multspc
-- TableData
--		growth
--		attack
--		effort
--		misc
-- PickupData

HP_INTERNAL = 1;
ATK_INTERNAL = 2;
DEF_INTERNAL = 3;
SPE_INTERNAL = 4;
SPA_INTERNAL = 5;
SPD_INTERNAL = 6;

PokemonData = {
	name = {
		"??????", "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", "Squirtle", 
		"Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree", "Weedle", "Kakuna", 
		"Beedrill", "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate", "Spearow", 
		"Fearow", "Ekans", "Arbok", "Pikachu", "Raichu", "Sandshrew", "Sandslash", 
		"Nidoran♀", "Nidorina", "Nidoqueen", "Nidoran♂", "Nidorino", "Nidoking", "Clefairy", 
		"Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff", "Zubat", "Golbat", 
		"Oddish", "Gloom", "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth", 
		"Diglett", "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck", "Mankey", 
		"Primeape", "Growlithe", "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath", "Abra", 
		"Kadabra", "Alakazam", "Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", 
		"Victreebel", "Tentacool", "Tentacruel", "Geodude", "Graveler", "Golem", "Ponyta", 
		"Rapidash", "Slowpoke", "Slowbro", "Magnemite", "Magneton", "Farfetch'd", "Doduo", 
		"Dodrio", "Seel", "Dewgong", "Grimer", "Muk", "Shellder", "Cloyster", 
		"Gastly", "Haunter", "Gengar", "Onix", "Drowzee", "Hypno", "Krabby", 
		"Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak", 
		"Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon", 
		"Chansey", "Tangela", "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", 
		"Staryu", "Starmie", "Mr. Mime", "Scyther", "Jynx", "Electabuzz", "Magmar", 
		"Pinsir", "Tauros", "Magikarp", "Gyarados", "Lapras", "Ditto", "Eevee", 
		"Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto", 
		"Kabutops", "Aerodactyl", "Snorlax", "Articuno", "Zapdos", "Moltres", "Dratini", 
		"Dragonair", "Dragonite", "Mewtwo", "Mew", "Chikorita", "Bayleef", "Meganium", 
		"Cyndaquil", "Quilava", "Typhlosion", "Totodile", "Croconaw", "Feraligatr", "Sentret", 
		"Furret", "Hoothoot", "Noctowl", "Ledyba", "Ledian", "Spinarak", "Ariados", 
		"Crobat", "Chinchou", "Lanturn", "Pichu", "Cleffa", "Igglybuff", "Togepi", 
		"Togetic", "Natu", "Xatu", "Mareep", "Flaaffy", "Ampharos", "Bellossom", 
		"Marill", "Azumarill", "Sudowoodo", "Politoed", "Hoppip", "Skiploom", "Jumpluff", 
		"Aipom", "Sunkern", "Sunflora", "Yanma", "Wooper", "Quagsire", "Espeon", 
		"Umbreon", "Murkrow", "Slowking", "Misdreavus", "Unown", "Wobbuffet", "Girafarig", 
		"Pineco", "Forretress", "Dunsparce", "Gligar", "Steelix", "Snubbull", "Granbull", 
		"Qwilfish", "Scizor", "Shuckle", "Heracross", "Sneasel", "Teddiursa", "Ursaring", 
		"Slugma", "Magcargo", "Swinub", "Piloswine", "Corsola", "Remoraid", "Octillery", 
		"Delibird", "Mantine", "Skarmory", "Houndour", "Houndoom", "Kingdra", "Phanpy", 
		"Donphan", "Porygon2", "Stantler", "Smeargle", "Tyrogue", "Hitmontop", "Smoochum", 
		"Elekid", "Magby", "Miltank", "Blissey", "Raikou", "Entei", "Suicune", 
		"Larvitar", "Pupitar", "Tyranitar", "Lugia", "Ho-Oh", "Celebi", "?", 
		"?", "?", "?", "?", "?", "?", "?", 
		"?", "?", "?", "?", "?", "?", "?", 
		"?", "?", "?", "?", "?", "?", "?", 
		"?", "?", "?", "Treecko", "Grovyle", "Sceptile", "Torchic", 
		"Combusken", "Blaziken", "Mudkip", "Marshtomp", "Swampert", "Poochyena", "Mightyena", 
		"Zigzagoon", "Linoone", "Wurmple", "Silcoon", "Beautifly", "Cascoon", "Dustox", 
		"Lotad", "Lombre", "Ludicolo", "Seedot", "Nuzleaf", "Shiftry", "Nincada", 
		"Ninjask", "Shedinja", "Taillow", "Swellow", "Shroomish", "Breloom", "Spinda", 
		"Wingull", "Pelipper", "Surskit", "Masquerain", "Wailmer", "Wailord", "Skitty", 
		"Delcatty", "Kecleon", "Baltoy", "Claydol", "Nosepass", "Torkoal", "Sableye", 
		"Barboach", "Whiscash", "Luvdisc", "Corphish", "Crawdaunt", "Feebas", "Milotic", 
		"Carvanha", "Sharpedo", "Trapinch", "Vibrava", "Flygon", "Makuhita", "Hariyama", 
		"Electrike", "Manectric", "Numel", "Camerupt", "Spheal", "Sealeo", "Walrein", 
		"Cacnea", "Cacturne", "Snorunt", "Glalie", "Lunatone", "Solrock", "Azurill", 
		"Spoink", "Grumpig", "Plusle", "Minun", "Mawile", "Meditite", "Medicham", 
		"Swablu", "Altaria", "Wynaut", "Duskull", "Dusclops", "Roselia", "Slakoth", 
		"Vigoroth", "Slaking", "Gulpin", "Swalot", "Tropius", "Whismur", "Loudred", 
		"Exploud", "Clamperl", "Huntail", "Gorebyss", "Absol", "Shuppet", "Banette", 
		"Seviper", "Zangoose", "Relicanth", "Aron", "Lairon", "Aggron", "Castform", 
		"Volbeat", "Illumise", "Lileep", "Cradily", "Anorith", "Armaldo", "Ralts", 
		"Kirlia", "Gardevoir", "Bagon", "Shelgon", "Salamence", "Beldum", "Metang", 
		"Metagross", "Regirock", "Regice", "Registeel", "Kyogre", "Groudon", "Rayquaza", 
		"Latias", "Latios", "Jirachi", "Deoxys", "Chimecho", "Bad Egg", "UNOWNB", 
		"UNOWNC", "UNOWND", "UNOWNE", "UNOWNF", "UNOWNG", "UNOWNH", "UNOWNI", 
		"UNOWNJ", "UNOWNK", "UNOWNL", "UNOWNM", "UNOWNN", "UNOWNO", "UNOWNP", 
		"UNOWNQ", "UNOWNR", "UNOWNS", "UNOWNT", "UNOWNU", "UNOWNV", "UNOWNW", 
		"UNOWNX", "UNOWNY", "UNOWNZ", "UNOWN!", "UNOWN?", "Turtwig", "Grotle", 
		"Torterra", "Chimchar", "Monferno", "Infernape", "Piplup", "Prinplup", "Empoleon", 
		"Starly", "Staravia", "Staraptor", "Bidoof", "Bibarel", "Kricketot", "Kricketune", 
		"Shinx", "Luxio", "Luxray", "Budew", "Roserade", "Cranidos", "Rampardos", 
		"Shieldon", "Bastiodon", "Burmy", "Wormadam", "Mothim", "Combee", "Vespiquen", 
		"Pachirisu", "Buizel", "Floatzel", "Cherubi", "Cherrim", "Shellos", "Gastrodon", 
		"Ambipom", "Drifloon", "Drifblim", "Buneary", "Lopunny", "Mismagius", "Honchkrow", 
		"Glameow", "Purugly", "Chingling", "Stunky", "Skuntank", "Bronzor", "Bronzong", 
		"Bonsly", "Mime Jr.", "Happiny", "Chatot", "Spiritomb", "Gible", "Gabite", 
		"Garchomp", "Munchlax", "Riolu", "Lucario", "Hippopotas", "Hippowdon", "Skorupi", 
		"Drapion", "Croagunk", "Toxicroak", "Carnivine", "Finneon", "Lumineon", "Mantyke", 
		"Snover", "Abomasnow", "Weavile", "Magnezone", "Lickilicky", "Rhyperior", "Tangrowth", 
		"Electivire", "Magmortar", "Togekiss", "Yanmega", "Leafeon", "Glaceon", "Gliscor", 
		"Mamoswine", "Porygon-Z", "Gallade", "Probopass", "Dusknoir", "Froslass", "Rotom", 
		"Uxie", "Mesprit", "Azelf", "Dialga", "Palkia", "Heatran", "Regigigas", 
		"Giratina", "Cresselia", "Phione", "Manaphy", "Darkrai", "Shaymin", "Arceus", 
		"Victini", "Snivy", "Servine", "Serperior", "Tepig", "Pignite", "Emboar", 
		"Oshawott", "Dewott", "Samurott", "Patrat", "Watchog", "Lillipup", "Herdier", 
		"Stoutland", "Purrloin", "Liepard", "Pansage", "Simisage", "Pansear", "Simisear", 
		"Panpour", "Simipour", "Munna", "Musharna", "Pidove", "Tranquill", "Unfezant", 
		"Blitzle", "Zebstrika", "Roggenrola", "Boldore", "Gigalith", "Woobat", "Swoobat", 
		"Drilbur", "Excadrill", "Audino", "Timburr", "Gurdurr", "Conkeldurr", "Tympole", 
		"Palpitoad", "Seismitoad", "Throh", "Sawk", "Sewaddle", "Swadloon", "Leavanny", 
		"Venipede", "Whirlipede", "Scolipede", "Cottonee", "Whimsicott", "Petilil", "Lilligant", 
		"Basculin", "Sandile", "Krokorok", "Krookodile", "Darumaka", "Darmanitan", "Maractus", 
		"Dwebble", "Crustle", "Scraggy", "Scrafty", "Sigilyph", "Yamask", "Cofagrigus", 
		"Tirtouga", "Carracosta", "Archen", "Archeops", "Trubbish", "Garbodor", "Zorua", 
		"Zoroark", "Minccino", "Cinccino", "Gothita", "Gothorita", "Gothitelle", "Solosis", 
		"Duosion", "Reuniclus", "Ducklett", "Swanna", "Vanillite", "Vanillish", "Vanilluxe", 
		"Deerling", "Sawsbuck", "Emolga", "Karrablast", "Escavalier", "Foongus", "Amoonguss", 
		"Frillish", "Jellicent", "Alomomola", "Joltik", "Galvantula", "Ferroseed", "Ferrothorn", 
		"Klink", "Klang", "Klinklang", "Tynamo", "Eelektrik", "Eelektross", "Elgyem", 
		"Beheeyem", "Litwick", "Lampent", "Chandelure", "Axew", "Fraxure", "Haxorus", 
		"Cubchoo", "Beartic", "Cryogonal", "Shelmet", "Accelgor", "Stunfisk", "Mienfoo", 
		"Mienshao", "Druddigon", "Golett", "Golurk", "Pawniard", "Bisharp", "Bouffalant", 
		"Rufflet", "Braviary", "Vullaby", "Mandibuzz", "Heatmor", "Durant", "Deino", 
		"Zweilous", "Hydreigon", "Larvesta", "Volcarona", "Cobalion", "Terrakion", "Virizion", 
		"Tornadus", "Thundurus", "Reshiram", "Zekrom", "Landorus", "Kyurem", "Keldeo", 
		"Meloetta", "Genesect", "Unfezant", "Frillish", "Jellicent", "Warrior", "Burmy", 
		"Burmy", "Wormadam", "Wormadam", "Shellos", "Gastrodon", "Rotom", "Rotom", 
		"Rotom", "Rotom", "Rotom", "Giratina", "Shaymin", "Arceus", "Arceus", 
		"Arceus", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus", 
		"Arceus", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus", 
		"Basculin", "Darmanitan", "Deerling", "Deerling", "Deerling", "Sawsbuck", "Sawsbuck", 
		"Sawsbuck", "Hippopotas", "Hippowdon", "Meloetta", "Genesect", "Genesect", "Genesect", 
		"Genesect", "Cherrim", "Kyurem", "Kyurem", "Tornadus", "Thundurus", "Landorus", 
		"Keldeo", "Chespin", "Quilladin", "Chesnaught", "Fennekin", "Braixen", "Delphox", 
		"Froakie", "Frogadier", "Greninja", "Bunnelby", "Diggersby", "Fletchling", "Fletchindr", 
		"Talonflame", "Scatterbug", "Spewpa", "Vivillon", "Litleo", "Pyroar", "Flabébé", 
		"Floette", "Florges", "Skiddo", "Gogoat", "Pancham", "Pangoro", "Furfrou", 
		"Espurr", "Meowstic", "Honedge", "Doublade", "Aegislash", "Spritzee", "Aromatisse", 
		"Swirlix", "Slurpuff", "Inkay", "Malamar", "Binacle", "Barbaracle", "Skrelp", 
		"Dragalge", "Clauncher", "Clawitzer", "Helioptile", "Heliolisk", "Tyrunt", "Tyrantrum", 
		"Amaura", "Aurorus", "Sylveon", "Hawlucha", "Dedenne", "Carbink", "Goomy", 
		"Sliggoo", "Goodra", "Klefki", "Phantump", "Trevenant", "Pumpkaboo", "Gourgeist", 
		"Bergmite", "Avalugg", "Noibat", "Noivern", "Xerneas", "Yveltal", "Zygarde", 
		"Diancie", "Hoopa", "Hoopa", "Volcanion", "Pyroar", "Meowstic", "Aegislash", 
		"Arceus", "Zygarde", "Zygarde", "Zygarde", "Zygarde", "Greninja", "Flabébé", 
		"Flabébé", "Flabébé", "Flabébé", "Floette", "Floette", "Floette", "Floette", 
		"Floette", "Florges", "Florges", "Florges", "Florges", "Pumpkaboo", "Pumpkaboo", 
		"Pumpkaboo", "Gourgeist", "Gourgeist", "Gourgeist", "Furfrou", "Furfrou", "Furfrou", 
		"Furfrou", "Furfrou", "Furfrou", "Furfrou", "Furfrou", "Furfrou", "Vivillon", 
		"Venusaur", "Charizard", "Charizard", "Blastoise", "Beedrill", "Pidgeot", "Alakazam", 
		"Slowbro", "Gengar", "Kangaskhan", "Pinsir", "Gyarados", "Aerodactyl", "Mewtwo", 
		"Mewtwo", "Ampharos", "Steelix", "Scizor", "Heracross", "Houndoom", "Tyranitar", 
		"Sceptile", "Blaziken", "Swampert", "Gardevoir", "Sableye", "Mawile", "Aggron", 
		"Medicham", "Manectric", "Sharpedo", "Camerupt", "Altaria", "Banette", "Absol", 
		"Glalie", "Salamence", "Metagross", "Latias", "Latios", "Groudon", "Kyogre", 
		"Rayquaza", "Lopunny", "Garchomp", "Lucario", "Abomasnow", "Gallade", "Audino", 
		"Diancie", "Dialga", "Palkia", "Vivillon", "Vivillon", "Vivillon", "Vivillon", 
		"Vivillon", "Vivillon", "Vivillon", "Vivillon", "Vivillon", "Vivillon", "Vivillon", 
		"Vivillon", "Vivillon", "Vivillon", "Vivillon", "Vivillon", "Vivillon", "Vivillon", 
		"Rowlet", "Dartrix", "Decidueye", "Litten", "Torracat", "Incineroar", "Popplio", 
		"Brionne", "Primarina", "Pikipek", "Trumbeak", "Toucannon", "Yungoos", "Gumshoos", 
		"Grubbin", "Charjabug", "Vikavolt", "Crabrawler", "Crabminble", "Oricorio", "Cutiefly", 
		"Ribombee", "Rockruff", "Lycanroc", "Wishiwashi", "Mareanie", "Toxapex", "Mudbray", 
		"Mudsdale", "Dewpider", "Araquanid", "Fomantis", "Lurantis", "Morelull", "Shiinotic", 
		"Salandit", "Salazzle", "Stufful", "Bewear", "Bounsweet", "Steenee", "Tsareena", 
		"Comfey", "Oranguru", "Passimian", "Wimpod", "Golisopod", "Sandygast", "Palossand", 
		"Pyukumuku", "Type: Null", "Silvally", "Minior", "Komala", "Turtonator", "Togedemaru", 
		"Mimikyu", "Bruxish", "Drampa", "Dhelmise", "Jangmo-o", "Hakamo-o", "Kommo-o", 
		"Tapu Koko", "Tapu Lele", "Tapu Bulu", "Tapu Fini", "Cosmog", "Cosmoem", "Solgaleo", 
		"Lunala", "Nihilego", "Buzzwole", "Pheromosa", "Xurkitree", "Celesteela", "Kartana", 
		"Guzzlord", "Necrozma", "Magearna", "Marshadow", "Rattata", "Raticate", "Raichu", 
		"Sandshrew", "Sandslash", "Vulpix", "Ninetales", "Diglett", "Dugtrio", "Meowth", 
		"Persian", "Geodude", "Graveler", "Golem", "Grimer", "Muk", "Exeggcute", 
		"Exeggutor", "Cubone", "Marowak", "Deoxys", "Deoxys", "Deoxys", "Oricorio", 
		"Oricorio", "Oricorio", "Lycanroc", "Wishiwashi", "Silvally", "Silvally", "Silvally", 
		"Silvally", "Silvally", "Silvally", "Silvally", "Silvally", "Silvally", "Silvally", 
		"Silvally", "Silvally", "Silvally", "Silvally", "Silvally", "Silvally", "Silvally", 
		"Minior", "Minior", "Minior", "Minior", "Minior", "Minior", "Minior", 
		"Mimikyu", "Magearna", "Poipole", "Naganadel", "Stakataka", "Blacphalon", "Zeraora", 
		"Necrozma", "Necrozma", "Necrozma", "Lycanroc", "Meltan", "Melmetal", "Pikachu", 
		"Pikachu", "Pikachu", "Pikachu", "Pikachu", "Pikachu", "Pikachu", "Pikachu", 
		"Pikachu", "Pikachu", "Pikachu", "Pikachu", "Pikachu", "Pikachu", "Pikachu", 
		"Pichu", "Xerneas", "Grookey", "Thwackey", "Rillaboom", "Scorbunny", "Raboot", 
		"Cinderace", "Sobble", "Drizzile", "Inteleon", "Skwovet", "Greedent", "Rookidee", 
		"Corvsquire", "Corvknight", "Blipbug", "Dottler", "Orbeetle", "Nickit", "Thievul", 
		"Gossifleur", "Eldegoss", "Wooloo", "Dubwool", "Chewtle", "Drednaw", "Yamper", 
		"Boltund", "Rolycoly", "Carkol", "Coalossal", "Applin", "Flapple", "Appletun", 
		"Silicobra", "Sandaconda", "Cramorant", "Arrokuda", "Baraskewda", "Toxel", "Toxtricity", 
		"Sizzlipede", "Centskorch", "Clobbopus", "Grapploct", "Sinistea", "Poltegeist", "Hatenna", 
		"Hattrem", "Hatterene", "Impidimp", "Morgrem", "Grimmsnarl", "Obstagoon", "Perrserker", 
		"Cursola", "Sirfetch'd", "Mr. Rime", "Runerigus", "Milcery", "Alcremie", "Falinks", 
		"Pincurchin", "Snom", "Frosmoth", "Stonjorner", "Eiscue", "Indeedee", "Morpeko", 
		"Cufant", "Copperajah", "Dracozolt", "Arctozolt", "Dracovish", "Arctovish", "Duraludon", 
		"Dreepy", "Drakloak", "Dragapult", "Zacian", "Zamazenta", "Eternatus", "Kubfu", 
		"Urshifu", "Zarude", "??????", "Calyrex", "Regieleki", "Regidrago", "Cramorant", 
		"Cramorant", "Toxtricity", "Sinistea", "Poltegeist", "Alcremie", "Alcremie", "Alcremie", 
		"Alcremie", "Alcremie", "Alcremie", "Eiscue", "Indeedee", "Morpeko", "Zacian", 
		"Zamazenta", "Eternatus", "Urshifu", "Meowth", "Ponyta", "Rapidash", "Slowpoke", 
		"Slowbro", "Farfetch'd", "Koffing", "Weezing", "Mr. Mime", "Articuno", "Zapdos", 
		"Moltres", "Slowking", "Corsola", "Zigzagoon", "Linoone", "Mime Jr.", "Darumaka", 
		"Darmanitan", "Darmanitan", "Yamask", "Stunfisk", "Venusaur", "Charizard", "Blastoise", 
		"Butterfree", "Pikachu", "Meowth", "Machamp", "Gengar", "Kingler", "Lapras", 
		"Eevee", "Snorlax", "Garbodor", "Melmetal", "Rillaboom", "Cinderace", "Inteleon", 
		"Corvknight", "Orbeetle", "Drednaw", "Coalossal", "Flapple", "Appletun", "Sandaconda", 
		"Toxtricity", "Toxtricity", "Centskorch", "Hatterene", "Grimmsnarl", "Alcremie", "Copperajah", 
		"Duraludon", "Urshifu", "Urshifu", "Calyrex", "Calyrex", "Spectrier", "Glastrier"
	},
	move = {
		"-", "Pound", "Karate Chop", "Double Slap", "Comet Punch", "Mega Punch", "Pay Day", "Fire Punch", 
		"Ice Punch", "ThunderPunch", "Scratch", "Vise Grip", "Guillotine", "Razor Wind", "Swords Dance", 
		"Cut", "Gust", "Wing Attack", "Whirlwind", "Fly", "Bind", "Slam", 
		"Vine Whip", "Stomp", "Double Kick", "Mega Kick", "Jump Kick", "Rolling Kick", "Sand Attack", 
		"Headbutt", "Horn Attack", "Fury Attack", "Horn Drill", "Tackle", "Body Slam", "Wrap", 
		"Take Down", "Thrash", "Double-Edge", "Tail Whip", "Poison Sting", "Twineedle", "Pin Missile", 
		"Leer", "Bite", "Growl", "Roar", "Sing", "Supersonic", "Sonic Boom", 
		"Disable", "Acid", "Ember", "Flamethrower", "Mist", "Water Gun", "Hydro Pump", 
		"Surf", "Ice Beam", "Blizzard", "Psybeam", "Bubble Beam", "Aurora Beam", "Hyper Beam", 
		"Peck", "Drill Peck", "Submission", "Low Kick", "Counter", "Seismic Toss", "Strength", 
		"Absorb", "Mega Drain", "Leech Seed", "Growth", "Razor Leaf", "Solar Beam", "PoisonPowder", 
		"Stun Spore", "Sleep Powder", "Petal Dance", "String Shot", "Dragon Rage", "Fire Spin", "ThunderShock", 
		"Thunderbolt", "Thunder Wave", "Thunder", "Rock Throw", "Earthquake", "Soul Robbery", "Dig", 
		"Toxic", "Confusion", "Psychic", "Hypnosis", "Meditate", "Agility", "Quick Attack", 
		"Rage", "Teleport", "Night Shade", "Mimic", "Screech", "Double Team", "Recover", 
		"Harden", "Minimize", "Smokescreen", "Confuse Ray", "Withdraw", "Defense Curl", "Barrier", 
		"Light Screen", "Haze", "Reflect", "Focus Energy", "Bide", "Metronome", "Mirror Move", 
		"Selfdestruct", "Egg Bomb", "Lick", "Smog", "Sludge", "Bone Club", "Fire Blast", 
		"Waterfall", "Clamp", "Swift", "Skull Bash", "Spike Cannon", "Constrict", "Amnesia", 
		"Kinesis", "Soft-Boiled", "Hi Jump Kick", "Glare", "Dream Eater", "Poison Gas", "Barrage", 
		"Leech Life", "Lovely Kiss", "Sky Attack", "Transform", "Bubble", "Dizzy Punch", "Spore", 
		"Flash", "Psywave", "Splash", "Acid Armor", "Crabhammer", "Explosion", "Fury Swipes", 
		"Bonemerang", "Rest", "Rock Slide", "Hyper Fang", "Sharpen", "Dark Hole", "Tri Attack", 
		"Super Fang", "Slash", "Substitute", "Struggle", "Sketch", "Triple Kick", "Thief", 
		"Spider Web", "Mind Reader", "Nightmare", "Flame Wheel", "Snore", "Curse", "Flail", 
		"Conversion 2", "Aeroblast", "Cotton Spore", "Reversal", "Spite", "Powder Snow", "Protect", 
		"Mach Punch", "Scary Face", "Feint Attack", "Sweet Kiss", "Belly Drum", "Sludge Bomb", "Mud-Slap", 
		"Octazooka", "Spikes", "Zap Cannon", "Foresight", "Destiny Bond", "Perish Song", "Icy Wind", 
		"Detect", "Bone Rush", "Lock-On", "Outrage", "Sandstorm", "Giga Drain", "Endure", 
		"Charm", "Rollout", "False Swipe", "Swagger", "Milk Drink", "Spark", "Fury Cutter", 
		"Steel Wing", "Mean Look", "Attract", "Sleep Talk", "Heal Bell", "Return", "Present", 
		"Frustration", "Safeguard", "Pain Split", "Sacred Fire", "Magnitude", "DynamicPunch", "Megahorn", 
		"DragonBreath", "Baton Pass", "Encore", "Pursuit", "Rapid Spin", "Sweet Scent", "Iron Tail", 
		"Metal Claw", "Vital Throw", "Morning Sun", "Synthesis", "Moonlight", "Hidden Power", "Cross Chop", 
		"Twister", "Rain Dance", "Sunny Day", "Crunch", "Mirror Coat", "Psych Up", "Extremespeed", 
		"AncientPower", "Shadow Ball", "Future Sight", "Rock Smash", "Whirlpool", "Beat Up", "Fake Out", 
		"Uproar", "Stockpile", "Spit Up", "Swallow", "Heat Wave", "Hail", "Torment", 
		"Flatter", "Will-O-Wisp", "Memento", "Facade", "Focus Punch", "SmellingSalt", "Follow Me", 
		"Nature Power", "Charge", "Taunt", "Helping Hand", "Trick", "Role Play", "Wish", 
		"Assist", "Ingrain", "Superpower", "Magic Coat", "Recycle", "Revenge", "Brick Break", 
		"Yawn", "Knock Off", "Endeavor", "Eruption", "Skill Swap", "Imprison", "Refresh", 
		"Grudge", "Snatch", "Secret Power", "Dive", "Arm Thrust", "Camouflage", "Tail Glow", 
		"Luster Purge", "Mist Ball", "FeatherDance", "Teeter Dance", "Blaze Kick", "Mud Sport", "Ice Ball", 
		"Needle Arm", "Slack Off", "Hyper Voice", "Poison Fang", "Crush Claw", "Blast Burn", "Hydro Cannon", 
		"Meteor Mash", "Astonish", "Weather Ball", "Aromatherapy", "Fake Tears", "Air Cutter", "Overheat", 
		"Odor Sleuth", "Rock Tomb", "Silver Wind", "Metal Sound", "Grasswhistle", "Tickle", "Cosmic Power", 
		"Water Spout", "Signal Beam", "Shadow Punch", "Extrasensory", "Sky Uppercut", "Sand Tomb", "Sheer Cold", 
		"Muddy Water", "Bullet Seed", "Aerial Ace", "Icicle Spear", "Iron Defense", "Block", "Howl", 
		"Dragon Claw", "Frenzy Plant", "Bulk Up", "Bounce", "Mud Shot", "Poison Tail", "Covet", 
		"Volt Tackle", "Magical Leaf", "Water Sport", "Calm Mind", "Leaf Blade", "Dragon Dance", "Rock Blast", 
		"Shock Wave", "Water Pulse", "Doom Desire", "Psycho Boost", "Leech Fang", "Air Slash", "Aqua Jet", 
		"Aqua Tail", "Aura Sphere", "Avalanche", "Brave Bird", "Bug Buzz", "Bullet Punch", "Charge Beam", 
		"Close Combat", "Cross Poison", "Dark Pulse", "Discharge", "Draco Meteor", "Dragon Pulse", "Drain Punch", 
		"Earth Power", "Energy Ball", "Focus Blast", "Force Palm", "Giga Impact", "Grass Knot", "Gunk Shot", 
		"Hammer Arm", "Head Smash", "Ice Shard", "Iron Head", "Lava Plume", "Magnet Bomb", "Mud Bomb", 
		"Nasty Plot", "Night Slash", "Ominous Wind", "Power Gem", "Power Whip", "Psycho Cut", "Rock Climb", 
		"Rock Polish", "Rock Wrecker", "Roost", "Seed Bomb", "Shadow Claw", "Shadow Sneak", "Vacuum Wave", 
		"X-Scissor", "Zen Headbutt", "Switcheroo", "Drill Run", "Bulldoze", "Electroweb", "Flame Charge", 
		"Frost Breath", "Heart Stamp", "Hone Claws", "Horn Leech", "Coil", "Hurricane", "Icicle Crash", 
		"Work Up", "Quiver Dance", "Leaf Tornado", "Low Sweep", "Snarl", "Struggle Bug", "Steamroller", 
		"Storm Throw", "Venoshock", "Wild Charge", "Poison Jab", "Acid Spray", "Fiery Dance", "Clear Smog", 
		"Leaf Storm", "Stone Edge", "Payback", "Fire Fang", "Ice Fang", "Thunder Fang", "Flare Blitz", 
		"Inferno", "Hex", "Dual Chop", "Double Hit", "Cotton Guard", "Acrobatics", "Flame Burst", 
		"U-turn", "Volt Switch", "Dragon Tail", "Circle Throw", "Mirror Shot", "Wood Hammer", "Heal Pulse", 
		"Flash Cannon", "Bug Bite", "Pluck", "Shell Smash", "Rage Powder", "Wake-Up Slap", "Razor Shell", 
		"Copycat", "Miracle Eye", "Sucker Punch", "Scald", "Brine", "Fairy Wind", "Doll Eyes", 
		"Play Rough", "Moonblast", "Drain Kiss", "Dazzle Gleam", "Disarm Cry", "Stealth Rock", "Toxic Spikes", 
		"Healing Wish", "Lunar Dance", "Tailwind", "Boomburst", "Incinerate", "Worry Seed", "Gastro Acid", 
		"Geomancy", "Flower Guard", "Rototiller", "Shift Gear", "Sticky Web", "Stored Power", "Acupressure", 
		"Punishment", "Assurance", "Dragon Rush", "Dark Void", "Feint", "PhantomForce", "Petal Storm", 
		"Play Nice", "Roar of Time", "Spacial Rend", "Magma Storm", "Final Gambit", "Shadow Force", "Nuzzle", 
		"Retaliate", "Metal Bash", "Judgment", "Freeze-Dry", "Psyshock", "Round", "Tail Slap", 
		"Gear Grind", "Natural Gift", "Chip Away", "Smack Down", "Space Hole", "Gyro Ball", "Space Fury", 
		"Attack Order", "Defend Order", "Heal Order", "Captivate", "Defog", "Origin Pulse", "Cliff Blades", 
		"Guard Swap", "Steam Pump", "Metal Burst", "Me First", "Power Swap", "Power Trick", "Psycho Shift", 
		"Wring Out", "Kings Shield", "Psystrike", "Autotomize", "DiamondStorm", "Sludge Wave", "Heavy Slam", 
		"Synchronoise", "Electro Ball", "Foul Play", "Entrainment", "Night Daze", "Echoed Voice", "Land's Wrath", 
		"OblivionWing", "Heart Swap", "Aqua Fang", "Sacred Sword", "Heat Crash", "Head Charge", "Techno Blast", 
		"Relic Song", "Secret Sword", "Glaciate", "Bolt Strike", "Blue Flare", "Freeze Shock", "Ice Burn", 
		"V-create", "Fusion Flare", "Fusion Bolt", "Fell Stinger", "Noble Roar", "Dragon Rise", "Parting Shot", 
		"Topsy-Turvy", "Core Enforce", "Chatter", "Confide", "Water Star", "Mystic Fire", "Spiky Shield", 
		"EerieImpulse", "Hold Back", "Infestation", "Power-Up Hit", "1000 Arrows", "1000 Waves", "Para Charge", 
		"Searing Shot", "Seed Flare", "Accelerock", "Anchor Shot", "Aurora Veil", "Baneful Bunk", "Beak Blast", 
		"Brutal Swing", "Burn Up", "Clang Scales", "Dark Lariat", "Draco Hammer", "Fire Lash", "FirstImpress", 
		"Fleur Cannon", "Floral Heal", "Gear Up", "HiHorsepower", "Ice Hammer", "Laser Focus", "Leafage", 
		"Liquidation", "Lunge", "Geist Beam", "Multi-Attack", "Nature's Mad", "Pollen Puff", "Power Trip", 
		"Prism Laser", "Psychic Fang", "Purify", "Revel Dance", "Shadow Bone", "Shell Trap", "Shore Up", 
		"Smart Strike", "Solar Blade", "Sparkle Aria", "Spect Thief", "Speed Swap", "Spirit Lock", "Spotlight", 
		"Bad Tantrum", "Strength Sap", "Sunsteel Ram", "Teary Look", "Throat Chop", "Toxic Thread", "Trop Kick", 
		"Zing Zap", "Elec Terrain", "Gras Terrain", "Mist Terrain", "Psyc Terrain", "Grass Pledge", "Fire Pledge", 
		"Water Pledge", "Trick Room", "Magic Room", "Wonder Room", "Crafty Guard", "Mat Block", "Quick Guard", 
		"Wide Guard", "Aqua Ring", "Aroma Mist", "Belch", "Bestow", "Fling", "Flying Press", 
		"Gravity", "Guard Split", "Heal Block", "Ion Deluge", "Lucky Chant", "Magnet Rise", "Magnet Flux", 
		"Powder", "Power Split", "Reflect Type", "Simple Beam", "Soak", "Telekinesis", "TrickoTreat", 
		"Venom Drench", "Woods Curse", "Mind Blown", "PhotonGeyser", "Plasma Fists", "Electrify", "Embargo", 
		"Fairy Lock", "Light ofRuin", "Trump Card", "After You", "Instruct", "Quash", "Happy Hour", 
		"Double Iron", "Last Resort", "Sky Drop", "Celebrate", "Hold Hands", "DMax Cannon", "Snipe Shot", 
		"Jaw Lock", "Stuff Cheeks", "No Retreat", "Tar Shot", "Magic Powder", "Dragon Darts", "Teatime", 
		"Octolock", "Bolt Beak", "FishiousRend", "Court Change", "Clang Soul", "Body Press", "Decorate", 
		"Drum Beating", "Snap Trap", "Pyro Ball", "Giant Blade", "Giant Bash", "Aura Wheel", "Break Swipe", 
		"Branch Poke", "Overdrive", "Apple Acid", "Grav Apple", "Spirit Break", "Weird Steam", "Life Dew", 
		"Obstruct", "False Yield", "Meteor Rush", "Eternabeam", "Steel Beam", "Expand Force", "Steel Roller", 
		"Scale Shot", "Meteor Beam", "ShellSideArm", "MistyExplode", "Grassy Glide", "Rising Volt", "TerrainPulse", 
		"SkitterSmack", "Jealous Burn", "Lash Out", "Poltergeist", "Corrode Gas", "Coaching", "Flip Turn", 
		"Triple Axel", "DualWingbeat", "Scorch Sands", "Jungle Heal", "Wicked Blow", "SurgeStrikes", "Freeze Glare", 
		"Thunder Kick", "Fiery Wrath", "Thunder Cage", "DragonEnergy", "Z-Move 1", "Z-Move 2", "Z-Move 3", 
		"Z-Move 4", "Z-Move 5", "Z-Move 6", "Z-Move 7", "Z-Move 8", "Z-Move 9", "Z-Move 10", 
		"Z-Move 11", "Z-Move 12", "Z-Move 13", "Z-Move 14", "Z-Move 15", "Z-Move 16", "Z-Move 17", 
		"Z-Move 18", "Z-Move 19", "Z-Move 20", "Z-Move 21", "Z-Move 22", "Z-Move 23", "Z-Move 24", 
		"Z-Move 25", "Z-Move 26", "Z-Move 27", "Z-Move 28", "Z-Move 29", "Z-Move 30", "Z-Move 31", 
		"Z-Move 32", "Z-Move 33", "Z-Move 34", "Z-Move 35", "Z-Move 36", "Z-Move 37", "Z-Move 38", 
		"Z-Move 39", "Z-Move 40", "Z-Move 41", "Z-Move 42", "Z-Move 43", "Z-Move 44", "Z-Move 45", 
		"Z-Move 46", "Z-Move 47", "Z-Move 48", "Z-Move 49", "Z-Move 50", "Z-Move 51", "Z-Move 52", 
		"Z-Move 53", "Guard", "Strike", "Strike", "Knuckle", "Knuckle", "Airstream", 
		"Airstream", "Ooze", "Ooze", "Quake", "Quake", "Rockfall", "Rockfall", 
		"Flutterby", "Flutterby", "Phantasm", "Phantasm", "Steelspike", "Steelspike", "Flare", 
		"Flare", "Geyser", "Geyser", "Overgrowth", "Overgrowth", "Lightning", "Lightning", 
		"Mindstorm", "Mindstorm", "Hailstorm", "Hailstorm", "Wyrmwind", "Wyrmwind", "Darkness", 
		"Darkness", "Starfall", "Starfall", "Vine Lash", "Vine Lash", "Wildfire", "Wildfire", 
		"Cannonade", "Cannonade", "Befuddle", "Befuddle", "Voltcrash", "Voltcrash", "Goldrush", 
		"Goldrush", "Chistrike", "Chistrike", "Terror", "Terror", "Foamburst", "Foamburst", 
		"Resonance", "Resonance", "Cuddle", "Cuddle", "Replenish", "Replenish", "Malodor", 
		"Malodor", "Meltdown", "Meltdown", "Drum Solo", "Drum Solo", "Fireball", "Fireball", 
		"Hydrosnipe", "Hydrosnipe", "Windrage", "Windrage", "Gravitas", "Gravitas", "Stonesurge", 
		"Stonesurge", "Volcalith", "Volcalith", "Tartness", "Tartness", "Sweetness", "Sweetness", 
		"Sandblast", "Sandblast", "Stunshock", "Stunshock", "Centiferno", "Centiferno", "Smite", 
		"Smite", "Snooze", "Snooze", "Finale", "Finale", "Steelsurge", "Steelsurge", 
		"Depletion", "Depletion", "One Blow", "One Blow", "Rapid Flow", "Rapid Flow", 
	},
	moveLookup = {},
	nature = {
		"Hardy", "Lonely", "Brave", "Adamant", "Naughty",
		"Bold", "Docile", "Relaxed", "Impish", "Lax",
		"Timid", "Hasty", "Serious", "Jolly", "Naive",
		"Modest", "Mild", "Quiet", "Bashful", "Rash",
		"Calm", "Gentle", "Sassy", "Careful", "Quirky"
	},
	natureLookup = {},
	type = {
		"Normal","Fighting","Flying","Poison","Ground",
		"Rock","Bug","Ghost","Steel","???",
		"Fire","Water","Grass","Electric",
		"Psychic","Ice","Dragon","Dark","Type 18",
		"Type 19","Type 20","Type 21","Type 22","Fairy"
	},
	status = {
		"None","Sleep","Poison","Burn","Freeze",
		"Paralysis","Bad Poison"
	},
	ability = {
		"-------", "Stench", "Drizzle", "Speed Boost", "Battle Armor", "Sturdy", "Damp", "Limber", 
		"Sand Veil", "Static", "Volt Absorb", "Water Absorb", "Oblivious", "Cloud Nine", "Compound Eyes", 
		"Insomnia", "Color Change", "Immunity", "Flash Fire", "Shield Dust", "Own Tempo", "Suction Cups", 
		"Intimidate", "Shadow Tag", "Rough Skin", "Wonder Guard", "Levitate", "Effect Spore", "Synchronize", 
		"Clear Body", "Natural Cure", "Lightning Rod", "Serene Grace", "Swift Swim", "Chlorophyll", "Gulp Missile", 
		"Trace", "Huge Power", "Poison Point", "Inner Focus", "Magma Armor", "Water Veil", "Magnet Pull", 
		"Soundproof", "Rain Dish", "Sand Stream", "Pressure", "Thick Fat", "Early Bird", "Flame Body", 
		"Run Away", "Bad Company", "Hyper Cutter", "Pickup", "Truant", "Hustle", "Cute Charm", 
		"Plus", "Minus", "Forecast", "Sticky Hold", "Shed Skin", "Guts", "Marvel Scale", 
		"Liquid Ooze", "Overgrow", "Blaze", "Torrent", "Swarm", "Rock Head", "Drought", 
		"Arena Trap", "Vital Spirit", "White Smoke", "Neutralize Gas", "Shell Armor", "Hunger Switch", "Air Lock", 
		"Sweet Veil", "Skill Link", "Motor Drive", "Multiscale", "Technician", "Scrappy", "Super Luck", 
		"Sniper", "Regenerator", "Prankster", "Adaptability", "Big Pecks", "Magic Bounce", "Reckless", 
		"Sheer Force", "Iron Fist", "Rivalry", "Sand Force", "Solar Power", "Heatproof", "Dry Skin", 
		"Tinted Lens", "Solid Rock", "Filter", "Infiltrator", "Download", "Poison Heal", "Ice Body", 
		"Bull Rush", "Hydration", "Healer", "Snow Cloak", "Tangled Feet", "Snow Warning", "Quick Feet", 
		"Sap Sipper", "Overcoat", "Magic Guard", "Bulletproof", "Gale Wings", "Moxie", "Aftermath", 
		"Cursed Body", "Gooey", "Mummy", "Iron Barbs", "Sand Rush", "Analytic", "No Guard", 
		"Mega Launcher", "Tough Claws", "Strong Jaw", "Victory Star", "Storm Drain", "Dark Aura", "Fairy Aura", 
		"Aura Break", "Refrigerate", "Pixilate", "Aerilate", "Feline Prowess", "Unburden", "Simple", 
		"Unaware", "Defiant", "Competitive", "Defeatist", "Slow Start", "Toxic Boost", "Flare Boost", 
		"Fur Coat", "Wonder Skin", "Protean", "Parental Bond", "Mold Breaker", "Turboblaze", "Teravolt", 
		"Zen Mode", "Battle Bond", "Beast Boost", "Corrosion", "Disguise", "Emergency Exit", "Fluffy", 
		"Steely Spirit", "Perish Body", "Wandering Soul", "Power Construct", "Prism Armor", "ORAORAORAORA!", "Schooling", 
		"Shadow Shield", "Shields Down", "Slush Rush", "Soul-Heart", "Stamina", "Steelworker", "Tangling Hair", 
		"Triage", "Water Bubble", "Water Compact", "Parasitic Waste", "Multitype", "Electric Surge", "Grassy Surge", 
		"Misty Surge", "Psychic Surge", "Surge Surfer", "Grass Pelt", "Anger Point", "Anticipation", "Forewarn", 
		"Frisk", "Contrary", "Unnerve", "Weak Armor", "Heavy Metal", "Light Metal", "Steadfast", 
		"Imposter", "Justified", "Unseen Fist", "Merciless", "Aroma Veil", "Flower Veil", "Leaf Guard", 
		"Klutz", "Flower Gift", "Bad Dreams", "Icy Protector", "Portal Power", "Poison Touch", "Magician", 
		"Stance Change", "Primordial Sea", "Desolate Land", "Delta Stream", "Gorilla Tactics", "Berserk", "Primal Armor", 
		"Liquid Voice", "Queenly Majesty", "Innards Out", "Dazzling", "Gluttony", "Mountaineer", "Friend Guard", 
		"Harvest", "Telepathy", "Illusion", "Cheek Pouch", "Symbiosis", "Stakeout", "Comatose", 
		"Dancer", "Battery", "Receiver", "Alchemic Power", "Neuroforce", "Galvanize", "Intrepid Sword", 
		"Valiant Shield", "Striker", "Cotton Down", "Mirror Armor", "Blademaster", "Surprise!", "Steam Engine", 
		"Punk Rock", "Sand Spit", "Ice Scales", "Ripen", "Ice Face", "Power Spot", "Blazing Soul", 
		"Screen Cleaner", "Pastel Veil", "Sage Power", 
	},
	item = {
		"????????", "Master Ball", "Ultra Ball", "Great Ball", "Poké Ball", "Safari Ball", "Net Ball", "Dive Ball", 
		"Nest Ball", "Repeat Ball", "Timer Ball", "Luxury Ball", "Premier Ball", "Potion", "Antidote", 
		"Burn Heal", "Ice Heal", "Awakening", "Paralyz Heal", "Full Restore", "Max Potion", "Hyper Potion", 
		"Super Potion", "Full Heal", "Revive", "Max Revive", "Fresh Water", "Soda Pop", "Lemonade", 
		"Moomoo Milk", "EnergyPowder", "Energy Root", "Heal Powder", "Revival Herb", "Ether", "Max Ether", 
		"Elixir", "Max Elixir", "Lava Cookie", "Blue Flute", "Yellow Flute", "Red Flute", "Black Flute", 
		"White Flute", "Berry Juice", "Sacred Ash", "Shoal Salt", "Shoal Shell", "Red Shard", "Blue Shard", 
		"Yellow Shard", "Green Shard", "RageCandyBar", "Old Gateau", "Casteliacone", "Dream Pill", "ShalourSable", 
		"Health Wing", "Muscle Wing", "Resist Wing", "Genius Wing", "Clever Wing", "Swift Wing", "HP Up", 
		"Protein", "Iron", "Carbos", "Calcium", "Rare Candy", "PP Up", "Zinc", 
		"PP Max", "Ability Pill", "Guard Spec.", "Dire Hit", "X Attack", "X Defend", "X Speed", 
		"X Accuracy", "X Sp. Atk", "Poké Doll", "Fluffy Tail", "Big Malasada", "Super Repel", "Max Repel", 
		"Escape Rope", "Repel", "Link Cable", "Protector", "Electirizer", "Magmarizer", "Dubious Disc", 
		"Reaper Cloth", "Sun Stone", "Moon Stone", "Fire Stone", "ThunderStone", "Water Stone", "Leaf Stone", 
		"Shiny Stone", "Dusk Stone", "Dawn Stone", "Ice Stone", "TinyMushroom", "Big Mushroom", "BalmMushroom", 
		"Pearl", "Big Pearl", "Stardust", "Star Piece", "Nugget", "Heart Scale", "Rare Bone", 
		"Pearl String", "Comet Shard", "Big Nugget", "Honey", "Pretty Wing", "Oval Stone", "Razor Claw", 
		"Razor Fang", "Orange Mail", "Harbor Mail", "Glitter Mail", "Mech Mail", "Wood Mail", "Wave Mail", 
		"Bead Mail", "Shadow Mail", "Tropic Mail", "Dream Mail", "Fab Mail", "Retro Mail", "Cheri Berry", 
		"Chesto Berry", "Pecha Berry", "Rawst Berry", "Aspear Berry", "Leppa Berry", "Oran Berry", "Persim Berry", 
		"Lum Berry", "Sitrus Berry", "Figy Berry", "Wiki Berry", "Mago Berry", "Aguav Berry", "Iapapa Berry", 
		"Razz Berry", "Bluk Berry", "Nanab Berry", "Wepear Berry", "Pinap Berry", "Pomeg Berry", "Kelpsy Berry", 
		"Qualot Berry", "Hondew Berry", "Grepa Berry", "Tamato Berry", "Cornn Berry", "Magost Berry", "Rabuta Berry", 
		"Nomel Berry", "Spelon Berry", "Pamtre Berry", "Watmel Berry", "Durin Berry", "Belue Berry", "Liechi Berry", 
		"Ganlon Berry", "Salac Berry", "Petaya Berry", "Apicot Berry", "Lansat Berry", "Starf Berry", "Enigma Berry", 
		"Prism Scale", "Sachet", "Whip Dream", "BrightPowder", "White Herb", "Macho Brace", "Exp. Share", 
		"Quick Claw", "Soothe Bell", "Mental Herb", "Choice Band", "King's Rock", "SilverPowder", "Amulet Coin", 
		"Cleanse Tag", "Soul Dew", "DeepSeaTooth", "DeepSeaScale", "Smoke Ball", "Everstone", "Focus Band", 
		"Lucky Egg", "Scope Lens", "Metal Coat", "Leftovers", "Dragon Scale", "Light Ball", "Soft Sand", 
		"Hard Stone", "Miracle Seed", "BlackGlasses", "Black Belt", "Magnet", "Mystic Water", "Sharp Beak", 
		"Poison Barb", "Nevermeltice", "Spell Tag", "TwistedSpoon", "Charcoal", "Dragon Fang", "Silk Scarf", 
		"Upgrade", "Shell Bell", "Sea Incense", "Lax Incense", "Lucky Punch", "Metal Powder", "Thick Club", 
		"Leek Stick", "Straw. Sweet", "Berry Sweet", "Love Sweet", "Clover Sweet", "Flower Sweet", "Ribbon Sweet", 
		"Star Sweet", "Sweet Apple", "Tart Apple", "Cracked Pot", "Chipped Pot", "Galar Cuff", "Galar Crown", 
		"Cherish Ball", "Dusk Ball", "Heal Ball", "Quick Ball", "Fast Ball", "Level Ball", "Lure Ball", 
		"Heavy Ball", "Love Ball", "Friend Ball", "Moon Ball", "Sport Ball", "Beast Ball", "Dream Ball", 
		"Park Ball", "Red Scarf", "Blue Scarf", "Pink Scarf", "Green Scarf", "Yellow Scarf", "Mach Bike", 
		"Coin Case", "Itemfinder", "Old Rod", "Good Rod", "Super Rod", "S.S. Ticket", "Contest Pass", 
		"Z-Power Ring", "Wailmer Pail", "Devon Goods", "Soot Sack", "Basement Key", "Acro Bike", "\x55\x56\x57\x58\x59 CASE", 
		"Letter", "Eon Ticket", "Red Orb", "Blue Orb", "Scanner", "Go-Goggles", "Meteorite", 
		"RM. 1 Key", "RM. 2 Key", "RM. 4 Key", "RM. 6 Key", "Storage Key", "Root Fossil", "Claw Fossil", 
		"Devon Scope", "TM01", "TM02", "TM03", "TM04", "TM05", "TM06", 
		"TM07", "TM08", "TM09", "TM10", "TM11", "TM12", "TM13", 
		"TM14", "TM15", "TM16", "TM17", "TM18", "TM19", "TM20", 
		"TM21", "TM22", "TM23", "TM24", "TM25", "TM26", "TM27", 
		"TM28", "TM29", "TM30", "TM31", "TM32", "TM33", "TM34", 
		"TM35", "TM36", "TM37", "TM38", "TM39", "TM40", "TM41", 
		"TM42", "TM43", "TM44", "TM45", "TM46", "TM47", "TM48", 
		"TM49", "TM50", "HM01", "HM02", "HM03", "HM04", "HM05", 
		"HM06", "HM07", "HM08", "Dynamax Band", "Gold Teeth", "Oak's Parcel", "Poké Flute", 
		"Secret Key", "Bike Voucher", "Mega Ring", "Old Amber", "Card Key", "Lift Key", "Helix Fossil", 
		"Dome Fossil", "Silph Scope", "Bicycle", "Town Map", "Stat Scanner", "Fame Checker", "TM Case", 
		"Berry Pouch", "Teachy TV", "Tri-Pass", "Rainbow Pass", "Tea", "Mystic Ticket", "Aurora Ticket", 
		"Powder Jar", "Ruby", "Sapphire", "-DONT USE-", "TM51", "TM52", "TM53", 
		"TM54", "TM55", "TM56", "TM57", "TM58", "TM59", "TM60", 
		"TM61", "TM62", "TM63", "TM64", "TM65", "TM66", "TM67", 
		"TM68", "TM69", "TM70", "TM71", "TM72", "TM73", "TM74", 
		"TM75", "TM76", "TM77", "TM78", "TM79", "TM80", "TM81", 
		"TM82", "TM83", "TM84", "TM85", "TM86", "TM87", "TM88", 
		"TM89", "TM90", "TM91", "TM92", "TM93", "TM94", "TM95", 
		"TM96", "TM97", "TM98", "TM99", "TM100", "TM101", "TM102", 
		"TM103", "TM104", "TM105", "TM106", "TM107", "TM108", "TM109", 
		"TM110", "TM111", "TM112", "TM113", "TM114", "TM115", "TM116", 
		"TM117", "TM118", "TM119", "TM120", "Occa Berry", "Passho Berry", "Wacan Berry", 
		"Rindo Berry", "Yache Berry", "Chople Berry", "Kebia Berry", "Shuca Berry", "Coba Berry", "Payapa Berry", 
		"Tanga Berry", "Charti Berry", "Kasib Berry", "Haban Berry", "Colbur Berry", "Babiri Berry", "Chilan Berry", 
		"Micle Berry", "Custap Berry", "Jacoba Berry", "Rowap Berry", "Roseli Berry", "Kee Berry", "Marang Berry", 
		"Oval Charm", "Shiny Charm", "Rainbow Wing", "Silver Wing", "Magma Stone", "Light Stone", "Dark Stone", 
		"Sun Flute", "Moon Flute", "Gracidea", "DNA Splicers", "Reveal Glass", "PrisonBottle", "N-Solarizer", 
		"N-Lunarizer", "Rusty Sword", "Rusty Shield", "Adamant Orb", "Lustrous Orb", "Griseous Orb", "Fist Plate", 
		"Sky Plate", "Toxic Plate", "Earth Plate", "Stone Plate", "Insect Plate", "Spooky Plate", "Iron Plate", 
		"Flame Plate", "Splash Plate", "Meadow Plate", "Zap Plate", "Mind Plate", "Icicle Plate", "Draco Plate", 
		"Dread Plate", "Pixie Plate", "Fight Mem.", "Flying Mem.", "Poison Mem.", "Ground Mem.", "Rock Mem.", 
		"Bug Mem.", "Ghost Mem.", "Steel Mem.", "Fire Mem.", "Water Mem.", "Grass Mem.", "Electr Mem.", 
		"Psychic Mem.", "Ice Mem.", "Dragon Mem.", "Dark Mem.", "Fairy Mem.", "Burn Drive", "Douse Drive", 
		"Shock Drive", "Chill Drive", "Red Nectar", "YellowNectar", "Pink Nectar", "PurpleNectar", "Necrozium Z", 
		"Venusaurite", "CharzarditeX", "CharzarditeY", "Blastoisnite", "Beedrillite", "Pidgeotite", "Alakazite", 
		"Slowbronite", "Gengarite", "Kangaskanite", "Pinsirite", "Gyaradosite", "Aerodactlite", "MewtwoniteX", 
		"MewtwoniteY", "Ampharosite", "Steelixite", "Scizorite", "Heracronite", "Houndoomnite", "Tyranitarite", 
		"Sceptilite", "Blazikenite", "Swampertite", "Gardevoirite", "Sablenite", "Mawilite", "Aggronite", 
		"Medichamite", "Manectite", "Sharpedonite", "Cameruptite", "Altarianite", "Banettite", "Absolite", 
		"Glalitite", "Salamencite", "Metagrossite", "Latiasite", "Latiosite", "Lopunnite", "Garchompite", 
		"Lucarionite", "Abomasite", "Galladite", "Audinite", "Diancite", "Normalium Z", "Fightinium Z", 
		"Flyinium Z", "Poisonium Z", "Groundium Z", "Rockium Z", "Buginium Z", "Ghostium Z", "Steelium Z", 
		"Firium Z", "Waterium Z", "Grassium Z", "Electrium Z", "Psychium Z", "Icium Z", "Dragonium Z", 
		"Darkinium Z", "Fairium Z", "Alorichium Z", "Decidium Z", "Eevium Z", "Incinium Z", "Kommonium Z", 
		"Lunalium Z", "Lycanium Z", "Marshadium Z", "Mewnium Z", "Mimikium Z", "Pikanium Z", "Pikshunium Z", 
		"Primarium Z", "Snorlium Z", "Solganium Z", "Tapunium Z", "Blk Apricorn", "Blu Apricorn", "Grn Apricorn", 
		"Pnk Apricorn", "Red Apricorn", "Wht Apricorn", "Ylw Apricorn", "Relic Copper", "Relic Silver", "Relic Gold", 
		"Relic Vase", "Relic Band", "Relic Statue", "Relic Crown", "Skull Fossil", "Armor Fossil", "Cover Fossil", 
		"Plume Fossil", "Jaw Fossil", "Sail Fossil", "Bird Fossil", "Fish Fossil", "Drake Fossil", "Dino Fossil", 
		"Odd Keystone", "Bottle Cap", "G.Bottle Cap", "Wish Piece", "Power Bracer", "Power Belt", "Power Lens", 
		"Power Band", "Power Anklet", "Power Weight", "Luck Incense", "Full Incense", "Odd Incense", "Pure Incense", 
		"Rock Incense", "Rose Incense", "Wave Incense", "Normal Gem", "Fighting Gem", "Flying Gem", "Poison Gem", 
		"Ground Gem", "Rock Gem", "Bug Gem", "Ghost Gem", "Steel Gem", "Fire Gem", "Water Gem", 
		"Grass Gem", "Electric Gem", "Psychic Gem", "Ice Gem", "Dragon Gem", "Dark Gem", "Fairy Gem", 
		"Wide Lens", "Muscle Band", "Wise Glasses", "Expert Belt", "Light Clay", "Life Orb", "Power Herb", 
		"Toxic Orb", "Flame Orb", "Quick Powder", "Focus Sash", "Zoom Lens", "Metronome", "Iron Ball", 
		"Lagging Tail", "Destiny Knot", "Black Sludge", "Icy Rock", "Smooth Rock", "Heat Rock", "Damp Rock", 
		"Grip Claw", "Choice Scarf", "Choice Specs", "Sticky Barb", "Shed Shell", "Big Root", "Eviolite", 
		"Float Stone", "Rocky Helmet", "Air Balloon", "Red Card", "Ring Target", "Binding Band", "Absorb Bulb", 
		"Cell Battery", "Eject Button", "WeaknessPol.", "Assault Vest", "LuminousMoss", "Snowball", "Safe Goggles", 
		"Adrenal Orb", "Terrain Ext.", "Protect Pads", "Electr. Seed", "Grassy Seed", "Misty Seed", "Psychic Seed", 
		"Eject Pack", "Room Service", "Blunder Pol.", "HeavyDBoots", "Ut. Umbrella", "Throat Spray", "Machampite", 
		"Laprasite", "Butterfrite", "Garbodorite", "Snorlaxite", "Kinglerite", "Toxtricitite", "Coalossite", 
		"Duraludite", "Drednawite", "Copperajite", "Applite", "Orbeetlite", "Grimmsnite", "Medicine", 
		"Centiskite", "Sandacondite", "Alcremite", "Free Space19", "Free Space20", "Free Space21", "Free Space22", 
	},
	itemLookup = {},
	stats = {
		"HP", "Atk", "Def", "SpA", "SpD", "Spe"
	},
	statsInternal = {
		"HP", "Atk", "Def", "Spe", "SpA", "SpD"
	},
	statsInternalLookup = {},
	natureModifier = {
		{ATK_INTERNAL, ATK_INTERNAL},
		{ATK_INTERNAL, DEF_INTERNAL},
		{ATK_INTERNAL, SPE_INTERNAL},
		{ATK_INTERNAL, SPA_INTERNAL},
		{ATK_INTERNAL, SPD_INTERNAL},

		{DEF_INTERNAL, ATK_INTERNAL},
		{DEF_INTERNAL, DEF_INTERNAL},
		{DEF_INTERNAL, SPE_INTERNAL},
		{DEF_INTERNAL, SPA_INTERNAL},
		{DEF_INTERNAL, SPD_INTERNAL},

		{SPE_INTERNAL, ATK_INTERNAL},
		{SPE_INTERNAL, DEF_INTERNAL},
		{SPE_INTERNAL, SPE_INTERNAL},
		{SPE_INTERNAL, SPA_INTERNAL},
		{SPE_INTERNAL, SPD_INTERNAL},

		{SPA_INTERNAL, ATK_INTERNAL},
		{SPA_INTERNAL, DEF_INTERNAL},
		{SPA_INTERNAL, SPE_INTERNAL},
		{SPA_INTERNAL, SPA_INTERNAL},
		{SPA_INTERNAL, SPD_INTERNAL},

		{SPD_INTERNAL, ATK_INTERNAL},
		{SPD_INTERNAL, DEF_INTERNAL},
		{SPD_INTERNAL, SPE_INTERNAL},
		{SPD_INTERNAL, SPA_INTERNAL},
		{SPD_INTERNAL, SPD_INTERNAL}
	}
}

TableData = {
	growth = {1,1,1,1,1,1, 2,2,3,4,3,4, 2,2,3,4,3,4, 2,2,3,4,3,4},
	attack = {2,2,3,4,3,4, 1,1,1,1,1,1, 3,4,2,2,4,3, 3,4,2,2,4,3},
	effort = {3,4,2,2,4,3, 3,4,2,2,4,3, 1,1,1,1,1,1, 4,3,4,3,2,2},
	misc   = {4,3,4,3,2,2, 4,3,4,3,2,2, 4,3,4,3,2,2, 1,1,1,1,1,1}
}

for k, v in pairs(PokemonData.nature) do
	PokemonData.natureLookup[v:lower()] = k - 1;
end

for k, v in pairs(PokemonData.statsInternal) do
	PokemonData.statsInternalLookup[v:lower()] = k - 1;
end

for k, v in pairs(PokemonData.move) do
	PokemonData.moveLookup[v:lower():gsub("%s+", "")] = k - 1;
end

for k, v in pairs(PokemonData.item) do
	PokemonData.itemLookup[v:lower():gsub("%s+", "")] = k - 1;
end
